{% set name = "measurement" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # building using the release on github has an issue. see: https://github.com/coddingtonbear/python-measurement/issues/27
  # from pypi
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8bca4f99521e4cfe8df4ca3eb086d36f1c713b6d102cb836980adca5874bee65

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python
    - pip
    - setuptools
    - pbr
  run:
    - python
    - six >=1.0
    - sympy >=0.7.3

test:
  imports:
    - measurement

about:
  home: "https://python-measurement.readthedocs.io/en/latest/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Easily use and manipulate unit-aware measurement objects in Python"
  description: |
    The package allows easy manipulation of unit-aware objects of Distance, Area,
    Energy, Speed, Temperature, Time, Volume and Weight measurements.
  dev_url: https://github.com/coddingtonbear/python-measurement

extra:
  recipe-maintainers:
    - adbeda
