{% set name = "measurement" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a16fe5a8bd72f3682285e87a0abe880d647bcf6e3bf9cc727eeb261d6163c07e

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
    - sphinx
    - pytest-runner
  run:
    - python >=3
    - six >=1.0
    - sympy >=0.7.3

test:
  imports:
    - measurement

about:
  home: https://python-measurement.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easily use and manipulate unit-aware measurement objects in Python
  description: |
    The package allows easy manipulation of unit-aware objects of Distance, Area,
    Energy, Speed, Temperature, Time, Volume and Weight measurements.
  dev_url: https://github.com/coddingtonbear/python-measurement

extra:
  recipe-maintainers:
    - mxr-conda
    - adbeda
    - oblute
    - rluria14
