travis:
  secure:
    BINSTAR_TOKEN: DpxmuEMbE8yMlY4Wh7GVO86TVKTIN0mNbEFCgImTxwo6oCgZwBT/4Ft7QPGQbQuYb/dJ080dBll+tYX/tCBApp3HZ4e6rs4oN0gWwrGekpvoBOLBqMg8dEbnlGLSVJVm3Bj+i/369oawR9x8CcR/0RJLRTYHuTnIeTjfgcYyn25Iifx2/UcGHiSGsig8S+aZ1bUurUsj4Ow93FNYM/l5d8laTDzFrSH8FMfYyDsrdcWlrMV+eKxc4coNXQlNc3IHz/KD+5dpz2jrhvwl6mYomGsnnYAGkOazyNeuoY8rjgL3Ftde1Vg4jk5LCEBpD48hCnPAkqeGW3dMRwDhv+TZQLfeQ+kJwDh7fOyM/ckQhDsu6o37KixpXD2ismaL7pV8xnrmhvnv+LNupZFrIJkDk2XgxwhatJ6RfVenBAfVjYPfUcIVcnsK6+FRmPgpmZ5QKl1WZLifGem8MGf9XNgq9W9TFpqLjArrUJj5SbucYQ+wGPj1J0H2sSdI8s3wElNR4wwgxoF9w/MW+zB0sWb2oc3JE27Bb5l9bLjPqp4lDMS1mf0C+bRICSlawDoUvB+KBA59FQU0iHr0rBOfdCSKe7eZAAv8nce3YeAH3FqSBpSIeSiqm22KbL1WZwvLqSqIC4P3ueCOfMaxBbbqQHkfcrUZopJ8L1B6lf2UZ3aJOGg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
